//
// A simple sequential MapReduce for WordCount
//

#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <vector>
#include <algorithm>
#include <map>

using namespace std;
int map_time=1;
typedef struct {
    string key;
    string val;
}
KeyVal;

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
// the out put: key:token val:times 
bool isLetter(char input){
    if('a'<=input&&input<='z') return true;
    if('A'<=input&&input<='Z') return true;
    return false;
}
void addToken(map<string,int>&tool,string token){
    map<string,int>::iterator it;
    it=tool.find(token);
    if(it==tool.end()){
        tool.insert(std::pair<string,int>(token,1));
    }else{
        it->second=it->second+1;
        }
}
vector<KeyVal> Map(const string &filename, const string &content)
{
    // Your code goes here
    // Hints: split contents into an array of words.
    vector<KeyVal> result;
    map<string,int> tool;
    map<string,int>::iterator it;
    int begin=0;
    int end;
    std::string token;
    while(begin<content.size()){
        if(isLetter(content[begin])){
            end=begin+1;
            while(end<content.size()){
                if(isLetter(content[end])){
                    end++;
                }else{
                    token=content.substr(begin,end-begin);
                    addToken(tool,token);  
                    begin=end+1; 
                    break;     
                }
            }
            if(end==content.size()){
                token=content.substr(begin,end-begin);
                addToken(tool,token);
                begin=end;
                break;
            }
        }else{
            begin++;
        }
    }
    it = tool.begin();
    while(it!=tool.end()){
        KeyVal temp;
        temp.key=it->first;
        temp.val=to_string(it->second);
        result.push_back(temp);
        it++;
    }
    return result;
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
string Reduce(const string &key, const vector <string> &values)
{
    // Your code goes here
    // Hints: return the number of occurrences of the word.
    int count=0;
    for(int i=0;i<values.size();i++){
        int temp=std::atoi((values[i]).c_str());
        count+=temp;
    }
    return to_string(count);
}

int main(int argc, char ** argv)
{
    if (argc < 2) {
        cout << "Usage: mrsequential inputfiles...\n";
        exit(1);
    }

    vector <string> filename;
    vector <KeyVal> intermediate;

    //
    // read each input file,
    // pass it to Map,
    // accumulate the intermediate Map output.
    //

    for (int i = 1; i < argc; ++i) {

        string filename = argv[i];
        string content;

        // Read the whole file into the buffer.
        getline(ifstream(filename), content, '\0');

        vector <KeyVal> KVA = Map(filename, content);
        //cout<<"KVA size= "<<KVA.size()<<endl;
        intermediate.insert(intermediate.end(), KVA.begin(), KVA.end());

    }

    //
    // a big difference from real MapReduce is that all the
    // intermediate data is in one place, intermediate[],
    // rather than being partitioned into NxM buckets.
    //

    sort(intermediate.begin(), intermediate.end(),
    	[](KeyVal const & a, KeyVal const & b) {
		return a.key < b.key;
	});

    //
    // call Reduce on each distinct key in intermediate[],
    // and print the result to mr-out-0.
    //
    //cout<<"the size of intermediate"<<" "<<intermediate.size()<<endl;
    for (unsigned int i = 0; i < intermediate.size();) {
        unsigned int j = i + 1;
        for (; j < intermediate.size() && intermediate[j].key == intermediate[i].key;)
            j++;

        vector < string > values;
        for (unsigned int k = i; k < j; k++) {
            values.push_back(intermediate[k].val);
        }

        string output = Reduce(intermediate[i].key, values);
        printf("%s %s\n", intermediate[i].key.data(), output.data());

        i = j;
    }
    return 0;
}

